export const locations = [
    "First Gate",
    "Second Gate",
    "Sports Center",
    "Faculty of Education",
    "Faculty of Arts",
    "Faculty of Science",
    "Faculty of Engineering",
    "Faculty of Environmental Sciences",
    "Faculty of Law",
    "Faculty of Management Sciences",
    "Faculty of Social Sciences",
    "Distance Learning Institute (DLI)",
    "New Hall Shopping Complex",
    "Unilag Pharmacy",
    "ISL Unilag",
    "Eni Njoku Hostel",
    "King Jaja Hostel",
    "Mariere Hostel",
    "Biobaku Hostel",
    "Sodeinde Hostel",
    "El Kanemi Hostel",
    "Fagunwa Hostel",
    "Kofo Ademola Hostel",
    "Madam Tinubu Hostel (MTH)",
    "Amina Hostel",
    "Makama Hostel",
    "Moremi Hostel",
    "Unilag Women Society Hostel (ULWS)",
    "Wema Bank",
    "GTB Bank",
    "UBA Bank",
    "Access Bank",
    "First Bank",
    "Unilag Microfinance Bank",
    "Unilag DSA Building",
    "Unilag Central Mosque",
    "Chapel of Christ Church",
    "St. Thomas More Catholic Chaplaincy",
    "Campus Cab Park",
    "Education Cab Park",
    "Main Library",
    "Unilag Health Centre",
    "Senate Building",
    "Lagoon Front",
    "Nithub",
    "Ozolua",
    "Scholars Suites",
    "Unilag Guest House",
    "Afe Babalola Auditorium",
    "J.F. Ade Ajayi Auditorium (Main Auditorium)",
    "Julius Berger Hall",
    "Tayo Aderinokun Lecture Theatre",
    "Jelili Adebisi Omotola Hall (Unilag Multipurpose Hall)",
    "Nurudeen Alao Auditorium",
    "Unilag Amphiteathre"
]